version: '3.8' # doc version

services:
  postgres: # db
    image: postgres:16-alpine
    container_name: expense-tracker-db

    environment:
      POSTGRES_DB: expensetracker_db
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data # data persistence

    networks:
      - expense-tracker-network

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USERNAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: # named volume
    driver: local

networks:
  expense-tracker-network:
    driver: bridge