version: '3.8' # doc version


services:
  #PostgresDB
  postgres: # db
    image: postgres:16-alpine
    container_name: expense-tracker-db
    restart: unless-stopped

    environment:
      POSTGRES_DB: ${DATABASE_NAME:-expensetracker_db}
      POSTGRES_USER: ${DATABASE_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_INITDB_ARGS: "-E UTF8 --locale=en_US.UTF-8"

    ports:
      - "${DATABASE_PORT:-5432}:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data # data persistence

    networks:
      - expense-tracker-network

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USERNAME:-postgres} -d ${DATABASE_NAME:-expensetracker_db}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  #Spring
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: expense-tracker-api
    restart: unless-stopped

    depends_on:
      postgres:
        condition: service_healthy

    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-prod}

      DATABASE_URL: jdbc:postgresql://postgres:5432/${DATABASE_NAME:-expensetracker_db}
      DATABASE_USERNAME: ${DATABASE_USERNAME:-postgres}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}

      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION:-86400000}

      PORT: ${PORT:-8080}

    ports:
      - "${APP_PORT:-8080}:8080"

    networks:
      - expense-tracker-network

    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/actuator/health" ]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 40s


volumes:
  postgres_data: # named volume
    driver: local

networks:
  expense-tracker-network:
    driver: bridge